
Traceback (most recent call last):
  File "tests/exceptions/source/backtrace/suppressed_expression_direct.py", line 16, in b_decorated
    a(1, 0)
  File "tests/exceptions/source/backtrace/suppressed_expression_direct.py", line 10, in a
    x / y
ZeroDivisionError: division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tests/exceptions/source/backtrace/suppressed_expression_direct.py", line 44, in <module>
    c_decorator()
> File "tests/exceptions/source/backtrace/suppressed_expression_direct.py", line 29, in c_decorator
    b_decorated()
  File "tests/exceptions/source/backtrace/suppressed_expression_direct.py", line 18, in b_decorated
    raise ValueError("NOK") from e
ValueError: NOK

Traceback (most recent call last):
  File "tests/exceptions/source/backtrace/suppressed_expression_direct.py", line 23, in b_not_decorated
    a(1, 0)
  File "tests/exceptions/source/backtrace/suppressed_expression_direct.py", line 10, in a
    x / y
ZeroDivisionError: division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tests/exceptions/source/backtrace/suppressed_expression_direct.py", line 45, in <module>
    c_context_manager()
> File "tests/exceptions/source/backtrace/suppressed_expression_direct.py", line 34, in c_context_manager
    b_not_decorated()
  File "tests/exceptions/source/backtrace/suppressed_expression_direct.py", line 25, in b_not_decorated
    raise ValueError("NOK") from e
ValueError: NOK

Traceback (most recent call last):
  File "tests/exceptions/source/backtrace/suppressed_expression_direct.py", line 23, in b_not_decorated
    a(1, 0)
  File "tests/exceptions/source/backtrace/suppressed_expression_direct.py", line 10, in a
    x / y
ZeroDivisionError: division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tests/exceptions/source/backtrace/suppressed_expression_direct.py", line 46, in <module>
    c_explicit()
> File "tests/exceptions/source/backtrace/suppressed_expression_direct.py", line 39, in c_explicit
    b_not_decorated()
  File "tests/exceptions/source/backtrace/suppressed_expression_direct.py", line 25, in b_not_decorated
    raise ValueError("NOK") from e
ValueError: NOK
